### ISSUE TITLE
В группировке инвалидировать не один элемент, всех братьев

### ISSUE THREAD

**Issue by marnikitta** [data-streams/data-streams#1]

**Comment by mrMakaronka** [comment]
Done: 337ad32

**Comment by marnikitta** [comment]
Не проходит [тест](https://github.com/data-streams/data-streams/blob/master/new-core/src/test/java/com/spbsu/datastream/core/graph/ops/GroupingTest.java#L54). Если откатить коммит, начнет проходить

**Comment by mrMakaronka** [comment]
@marnikitta, ок, гляну сегодня

**Comment by marnikitta** [comment]
@mrMakaronka, я закомментировал на время

**Comment by mrMakaronka** [comment]
Проблема была в [INVALIDATION_COMPARATOR](https://github.com/data-streams/data-streams/commit/f0e98a3800f1d3b8d0f9b2a1d3440c72cdbd3d75#diff-cdef96e7e73b011e803902231ee1e029L21). Из-за этого мы принимали за братьев элементы, которые на самом деле ими не являются.

**Comment by mrMakaronka** [comment]
f0e98a3
