### ISSUE TITLE
SumTest is not stable with multiple fronts

### ISSUE THREAD

**Issue by mrMakaronka** [data-streams/data-streams#13]

**Comment by marnikitta** [comment]
Группировка уверенно порождает аки, которые когда-то были закрыты в Ledger (isReported + xor==0)

**Comment by marnikitta** [comment]
Fixed: https://github.com/data-streams/data-streams/commit/277618977dd5dfe52838f31275adb0909066fe13

**Comment by marnikitta** [comment]
@mrMakaronka, если элементы порождались одним фронтом, им соответствовала одна AckTable. Перепроигрываемые элементы "защищались" более старыми, тем самым в AckTable не могли приходить аки на уже закрытые элементы.

В случае нескольких фронтов, элементы расходились по разным AckTable,  и та самая защита уже не работала.

Фикс: разрешить приходить акам из прошлого

**Comment by mrMakaronka** [comment]
@marnikitta, SumTest упал после последнего коммита. Вручную тесты перезапустил - прошли. Локально тоже все ок. Возможно, просто времени не хватило. Логи трэвиса в аттаче.
[sumtest-fails.txt](https://github.com/data-streams/data-streams/files/1128676/sumtest-fails.txt)

**Comment by marnikitta** [comment]
Да, не хватило

`16:52:48.505 [worker-akka.actor.default-dispatcher-17] INFO  a.r.RemoteActorRefProvider$RemoteDeadLetterActorRef akka://worker/deadLetters - Message [com.spbsu.datastream.core.front.RawData] without sender to Actor[akka://worker/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
`

**Comment by marnikitta** [comment]
Увеличил https://github.com/data-streams/data-streams/commit/9f9eb3f4804e639c4d8a7f1fefe27fe4890db2a4

**Comment by marnikitta** [comment]
Стабильно падает, при изменении конфигурации тревиса. Странности...

[build](https://travis-ci.org/data-streams/data-streams/builds/251434058)

[weird-fail.txt](https://github.com/data-streams/data-streams/files/1132889/weird-fail.txt)

**Comment by marnikitta** [comment]
Upd: иногда падает и при старой конфигурации. Времени вроде хватает

**Comment by marnikitta** [comment]
Fixed

https://github.com/data-streams/data-streams/commit/8dee022d37141aba4cfdc5a8908ac284c0d58163

**Comment by marnikitta** [comment]
Тревису опять не удалось пройти SumTest.

[SumTest-fail.txt](https://github.com/data-streams/data-streams/files/1145564/SumTest-fail.txt)

**Comment by marnikitta** [comment]
[travis-sum-test.txt](https://github.com/data-streams/data-streams/files/1169119/travis-sum-test.txt)

**Comment by mrMakaronka** [comment]
Еще одна попытка: 42af33d

**Comment by marnikitta** [comment]
Seems to be stable for a while
